image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - before: cd database && chmod +x setup.sh && ./setup.sh
    init: cd bookmonkey-rest-api && npm install
    command: cd bookmonkey-rest-api && npm run start
