image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: 'npm i -g @nestjs/cli && cd bookmonkey-rest-api && npm install'
    command: 'cd bookmonkey-rest-api && npm run start'